### ISSUE TITLE
Comparison with Consolas and Ligaturized Consolas

### ISSUE THREAD

**Issue by kolmogorov42** [ofolis/consolig#1]
Hi @ofolis, I'm back with some comments as I promised.

I took a screenshot of the same code in all three of the fonts and pasted it together:
![consolig_comparison](https://user-images.githubusercontent.com/20615940/70390568-577c2d00-19cc-11ea-8692-c4e318c1abd9.png)

I absolutely love how you made the lines in the ==, === etc ligatures spaced exactly like the two lines in the original = sign. One thing that doesn't quite add up is the slash in the != and !== signs being drawn a little bit too high.

Compound assignment operators aren't really ligatures except for /=, which seems fine to me.

I must admit I'm not a fan of the ligatures made up from < and >. I find the ones in Ligaturized Consolas look better overall. Though I love when the lower stroke in >= and <= is drawn horizontally. What doesn't look very nice are the < and > parts themselves.

Logic operators look fine to me, as they're made from standard Consolas glyphs.

Also, for some reason, the double quote character looks a tiny bit different in Consolig compared to the other samples.

I probably missed many other ligatures, but these are the first ones that I thought was worth inspecting.

**Comment by ofolis** [comment]
@kolmogorov42 I made the following changes:

- Modified the `>=` and `<=` glyphs
- Changed the top line height of all "not equal" comparison operators
- Fixed the export process reversing the glyph geometry direction
  - I checked the actual point geometry of the double quote glyph, and everything matches, the only difference was the order of the points being reversed. Maybe this will help?
  - The only other thing that may be happening is if the glyph substitution logic is somehow replacing the flat double quote with one of the special glyphs, but I think that's unlikely.

As for the other compound assignments, we can add those as ligatures in a separate issue, since that isn't a bug, just missing ligatures. I'll open that now.

Have a look at https://github.com/ofolis/consolig/releases/tag/v0.2.0-rc1 and let me know what you think.

**Comment by ofolis** [comment]
I am using another laptop with a 72dpi display. I am seeing weird artifacting. Now that I can do a comparison, I'll start trying to figure out what's up. (@kolmogorov42 )

**Comment by ofolis** [comment]
I opened #5 to track the artifacting issues, but 0.2.0 will at least get out the glyph changes.

**Comment by merlinaudio** [comment]
Just want to say that this is absolutely stunning work. Thank you for making Consolig and putting in so much effort to make it consistent with the original!!
