### ISSUE TITLE
italic ligature anomalies

### ISSUE THREAD

**Issue by 6643** [ofolis/consolig#21]
![a](https://user-images.githubusercontent.com/3087856/109409623-52d7d600-79cf-11eb-945e-22e31e23e4a1.png)

Thank you very much for the script!
It allows me to use consola with hyphens
but italic ligature anomalies
JetBrainsMono italic is ok

**Comment by ofolis** [comment]
This is a known limitation. I am using the "regular style" ligatures on all of the font styles. The `#[` is one of my ligatures while the standard `]` character is from Consolas. Therefore, the `]` looks correct in the italic style while `#[` looks incorrect. This issue is tracked in #8 . Closing this one. Feel free to add more observations over there if you'd like, but this is on the radar. Thanks!
